import Script from "next/script";
import "./globals.css";
import "@/public/assets/css/main.css"
import "@/public/assets/css/swiper-bundle.min.css"
import SvgRepository from "@/components/svg/SvgRepository";
import ClientApp from "@/client_side_scripts/ClientApp";
import ClientSwiper from "@/client_side_scripts/ClientSwiper";

export const metadata = {
	title: "cafe next",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="fa" dir="rtl">
			<body className="bg-gray-100 dark:bg-zinc-800 h-[2000px]">
				<Script src="/assets/js/darkMode.js" strategy="beforeInteractive" />
				<SvgRepository />
				{children}
				<ClientApp />
				<ClientSwiper />
			</body>
		</html>
	);
}